# name: Build and Deploy Packer AMI

#on:
  #push:
   # branches:
      #- main
  #pull_request:
   # branches:
    #  - main
  #    - main

#permissions:
  #id-token: write
  #contents: read

#jobs:
 # build:
  #  runs-on: ubuntu-latest
   # steps:
    #  - name: Checkout Repository
     #   uses: actions/checkout@v4

     # - name: Install Packer
      #  uses: hashicorp/setup-packer@v2
       # with:
       #   version: latest

     #- name: Configure AWS Credentials via OIDC
       # uses: aws-actions/configure-aws-credentials@v2
       # with:
       #   role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #    aws-region: us-east-1

      #- name: Validate Packer Template
      #  run: packer validate ami-template.pkr.hcl

     # - name: Build AMI
      #  run: packer build ami-template.pkr.hcl

name: Build and Deploy Packer AMI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Request GitHub OIDC Token
        id: id_token
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.actions.createOidcToken({});
            console.log(response.data.value);
            return response.data.value;

      - name: Debug OIDC Token Sub Value
        run: |
          echo "Fetching OIDC Token..."
          TOKEN="${{ steps.id_token.outputs.token }}"
          echo "Decoded OIDC Token Sub Value:"
          echo $TOKEN | jq -R 'split(".") | .[1] | @base64d | fromjson' | jq '.sub'

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Validate Packer Template
        run: packer validate ami-template.pkr.hcl

      - name: Build AMI
        run: packer build ami-template.pkr.hcl


