# name: Build and Deploy Packer AMI

#on:
  #push:
   # branches:
      #- main
  #pull_request:
   # branches:
    #  - main
  #    - main

#permissions:
  #id-token: write
  #contents: read

#jobs:
 # build:
  #  runs-on: ubuntu-latest
   # steps:
    #  - name: Checkout Repository
     #   uses: actions/checkout@v4

     # - name: Install Packer
      #  uses: hashicorp/setup-packer@v2
       # with:
       #   version: latest

     #- name: Configure AWS Credentials via OIDC
       # uses: aws-actions/configure-aws-credentials@v2
       # with:
       #   role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #    aws-region: us-east-1

      #- name: Validate Packer Template
      #  run: packer validate ami-template.pkr.hcl

     # - name: Build AMI
      #  run: packer build ami-template.pkr.hcl

name: Build and Deploy Packer AMI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Initialize Packer
        run: |
          echo "Running packer init to install required plugins..."
          packer init ami-template.pkr.hcl
          echo "Checking installed plugins..."
          ls -R ~/.config/packer/plugins
          echo "Packer initialization completed."

      - name: Debug OIDC Token Sub Value
        run: |
          echo "Fetching OIDC Token..."
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                  "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "Decoded OIDC Token Sub Value:"
          echo $TOKEN | jq -R 'split(".") | .[1] | @base64d | fromjson' | jq '.sub'
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: "https://token.actions.githubusercontent.com"

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Validate Packer Template
        run: |
          echo "Validating Packer Template..."
          packer validate ami-template.pkr.hcl
          echo "Validation Completed."

      - name: Build AMI
        run: |
          echo "Building AMI..."
          packer build ami-template.pkr.hcl
          echo "Build Completed."




